name: Upload SARIF

on:
  push:
    paths:
      - example-sql-injection.sarif

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: example-sql-injection.sarif

